services:
 pitstop-app:
   build: .
   container_name: pitstop-app
   ports:
     - "8000:8000"
   environment:
     DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
     DEBUG: ${DEBUG}
     DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
     DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
   volumes:
     - "fast_f1_cache:/var/cache/fastf1"
   env_file:
     - .env

volumes:
    fast_f1_cache:
      driver: local
