name: Build Docker Image

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract version from tag
        id: extract_version
        run: |
          TAG=${GITHUB_REF##*/}
          VERSION=${TAG#Tag-Deployment-}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Login to Docker Hub
        env:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          docker login -u $username -p $password

      - name: Build the Docker image
        run: |
          docker build . -f Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/pitstop:${{ env.VERSION }}

      - name: Push the Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/pitstop:${{ env.VERSION }}
